name: Version compatibility tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  version_compatibility_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Compile
        run: ./mvnw -B -ntp process-test-resources
      - name: ArchUnit 1.0
        run: ./mvnw -B -ntp compiler:testCompile surefire:test -Darchunit.version=1.0.1
      - name: ArchUnit 1.1
        run: ./mvnw -B -ntp compiler:testCompile surefire:test -Darchunit.version=1.1.0
      - name: ArchUnit 1.2
        run: ./mvnw -B -ntp compiler:testCompile surefire:test -Darchunit.version=1.2.0
      - name: Spring Boot 2.7
        run: ./mvnw -B -ntp compiler:testCompile surefire:test -Dspring-boot.version=2.7.18
      - name: Spring Boot 3.0
        run: ./mvnw -B -ntp compiler:testCompile surefire:test -Dspring-boot.version=3.0.13
      - name: Spring Boot 3.1
        run: ./mvnw -B -ntp compiler:testCompile surefire:test -Dspring-boot.version=3.1.6
      - name: Spring Boot 3.2
        run: ./mvnw -B -ntp compiler:testCompile surefire:test -Dspring-boot.version=3.2.0
